### ISSUE TITLE
Undefined property: PhpParser\Node\Param::$name

### ISSUE THREAD

**Issue by Ooypunk** [php-censor/phpdoc-checker#1]
Message: "PHP Notice:  Undefined property: PhpParser\Node\Param::$name in /[...]/vendor/php-censor/phpdoc-checker/src/FileProcessor.php on line 154"

Command: vendor/bin/phpdoc-checker --json --directory=./ --exclude="vendor"

The file that caused this:
[ArgParser.php.txt](https://github.com/php-censor/phpdoc-checker/files/6708175/ArgParser.php.txt)

**Comment by corpsee** [comment]
Fixed by #2.

**Comment by Ooypunk** [comment]
Confirmed.
