### ISSUE TITLE
symfony/console 5.* support

### ISSUE THREAD

**Issue by si-dge** [php-censor/phpdoc-checker#4]
Actual version of the package symfony/console for Laravel LTS version (8.\*) is 5.\*: https://github.com/laravel/laravel/blob/8.x/composer.json

But php-censor/phpdoc-checker depends version 4.\*. Because of this, checker cannot be use with laravel 8.

What are you think about updating the package symfony/console version?

**Comment by corpsee** [comment]
Fixed. You can use `master` branch or tag/version `3.0.1`.
